name: example
description: A sample command-line application.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.5.0-180

dependencies:
  dio: ^5.5.0+1
  macrofit:
    path: ../

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
