name: macrofit
description: "A macro version of retrofit.dart"
version: 0.0.2-alpha
homepage: https://github.com/surfstudio/macrofit

environment:
  sdk: ^3.5.0-180

dependencies:
  collection: ^1.18.0
  dio: ^5.5.0+1
  flutter:
    sdk: flutter
  macros: ^0.1.0-main.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
