name: macrofit
description: "A macro version of retrofit.dart"
version: 0.0.1
homepage:

environment:
  sdk: ^3.5.0-180

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
